#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
CONFIG="$ROOT/docs/publisher_contact.yaml"

if [[ ! -f "$CONFIG" ]]; then
  echo "Missing $CONFIG" >&2
  exit 1
fi

read_yaml() {
  ruby -ryaml -e "puts YAML.load_file('$CONFIG').fetch('$1')"
}

EMAIL="$(read_yaml support_email)"
PRIVACY_URL="$(read_yaml privacy_policy_url)"
SUPPORT_URL="$(read_yaml support_url)"
COPYRIGHT="$(read_yaml copyright)"
PUBLISHED="$(read_yaml policy_published)"

escape_dart() {
  printf "%s" "$1" | sed "s/'/\\\\'/g"
}

EMAIL_DART="$(escape_dart "$EMAIL")"
PRIVACY_DART="$(escape_dart "$PRIVACY_URL")"
SUPPORT_DART="$(escape_dart "$SUPPORT_URL")"
COPYRIGHT_DART="$(escape_dart "$COPYRIGHT")"

cat >"$ROOT/lib/config/publisher_contact.dart" <<EOF
// GENERATED by tool/apply_publisher_contact.sh — edit docs/publisher_contact.yaml instead.
const publisherSupportEmail = '$EMAIL_DART';
const publisherPrivacyPolicyUrl = '$PRIVACY_DART';
const publisherSupportUrl = '$SUPPORT_DART';
const publisherCopyright = '$COPYRIGHT_DART';
const publisherPolicyPublished = $PUBLISHED;
EOF

PRIVACY_DRAFT_BLOCK=""
if [[ "$PUBLISHED" != "true" ]]; then
  PRIVACY_DRAFT_BLOCK='**DRAFT: do not publish until the publisher supplies the support contact and
public policy URL.**

'
fi

cat >"$ROOT/docs/PRIVACY_POLICY.md" <<EOF
# LessDo Privacy Policy

${PRIVACY_DRAFT_BLOCK}Effective date: June 14, 2026.

## Summary

LessDo is a local-first task and focus app. Version 1.0 does not collect,
transmit, sell, or share personal data with the publisher or third parties. It
has no account system, advertising, analytics, tracking, or remote backend.

## Data Stored on the Device

Lists, tasks, reminders, settings, and focus history are stored locally in the
app's private container. Removing the app may remove this local data. LessDo
does not upload or synchronize it in version 1.0.

The app keeps a bounded diagnostic log containing event type, time, app
version, platform, and technical error type. It excludes task titles, list
names, notes, and exception messages. The log remains on the device unless the
user explicitly exports it.

## Optional System Features

- Notifications are requested only when the user creates or retries a reminder.
  Reminder text is delivered through Apple's local notification system.
- Face ID or Touch ID is optional. Authentication is performed by iOS, and
  LessDo does not receive or store biometric data.
- Sharing occurs only after the user chooses a share action. The user controls
  the destination through the iOS share sheet.
- Deep links use the registered \`lessdo\` URL scheme and are validated before
  they can create or open local content.

## Data Collection

LessDo does not collect data from the app. App Store Connect should be answered
with: **No, we do not collect data from this app.**

## Permissions

Version 1.0 may request notification and biometric authentication access. It
does not request location, calendar, contacts, camera, microphone, photo
library, Bluetooth, local network, or tracking permission.

## Contact

Publisher support email: \`$EMAIL\`

Public privacy policy URL: \`$PRIVACY_URL\`
EOF

if [[ "$PUBLISHED" != "true" ]]; then
  cat >>"$ROOT/docs/PRIVACY_POLICY.md" <<'EOF'

This draft becomes publishable only after both values are replaced with the
publisher's real contact details.
EOF
fi

perl -pi -e "s|- Support URL: .*|- Support URL: \`$SUPPORT_URL\`|" "$ROOT/docs/APP_STORE_METADATA.md"
perl -pi -e "s|- Copyright: .*|- Copyright: \`$COPYRIGHT\`|" "$ROOT/docs/APP_STORE_METADATA.md"
perl -pi -e "s|- Privacy policy URL: .*|- Privacy policy URL: \`$PRIVACY_URL\`|g" "$ROOT/docs/APP_STORE_METADATA.md"

for hosted in privacy.html support.html; do
  perl -pi -e "s/LESSDO_SUPPORT_EMAIL/$EMAIL/g" "$ROOT/docs/hosted/$hosted"
done

echo "Applied publisher contact from $CONFIG"
echo "GitHub Pages URLs:"
echo "  $PRIVACY_URL"
echo "  $SUPPORT_URL"
