// GENERATED by tool/apply_publisher_contact.sh — edit docs/publisher_contact.yaml instead.
const publisherSupportEmail = 'PUBLISHER_REQUIRED_SUPPORT_EMAIL';
const publisherPrivacyPolicyUrl = 'PUBLISHER_REQUIRED_PRIVACY_URL';
const publisherSupportUrl = 'PUBLISHER_REQUIRED_SUPPORT_URL';
const publisherCopyright = 'PUBLISHER_REQUIRED_COPYRIGHT';
const publisherPolicyPublished = false;
