// GENERATED by tool/apply_publisher_contact.sh — edit docs/publisher_contact.yaml instead.
const publisherSupportEmail = 'lessdo.support@nightelf.dev';
const publisherPrivacyPolicyUrl = 'https://ruancanghui-hub.github.io/lessdo/privacy.html';
const publisherSupportUrl = 'https://ruancanghui-hub.github.io/lessdo/support.html';
const publisherCopyright = 'Copyright © 2026 nightelf';
const publisherPolicyPublished = true;
